apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
### An ApplicationSet can be used to manage multiple argo-cd deployment in different namespace or clusters
metadata:
  name: argo-cd
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters:
        selector:
          matchLabels:
            name: in-cluster
  template:
    metadata:
      name: "argo-cd.{{name}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .
    spec:
      destination:
        namespace: argocd
        name: "{{name}}"
      project: setup
      source:
        path: services/argo-cd
        repoURL: https://github.com/agaudreault/gitops-tests
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - FailOnSharedResource=true
          - ApplyOutOfSyncOnly=false
          # - RespectIgnoreDifferences=true ## Ignore labels and annotations from diff in case we apply manually
      ignoreDifferences:
        - group: "*"
          kind: "*"
          jsonPointers:
            - /metadata/labels
            - /metadata/annotations
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy ## Allow to disable sync for ArgoCD in the UI
